FROM golang:1.22.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o stock-publisher

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/stock-publisher /app/stock-publisher

CMD ["./stock-publisher"]
